
name: WaterGrief-AntiCheat
version: 2.0
main: me.watergrief.anticheat.WaterGriefAntiCheat
api-version: 1.16
author: WaterGrief
permissions:
  watergrief.alerts:
    description: Получать уведомления античита
    default: op
